namespacePrefixes:
  adms: http://www.w3.org/ns/adms#
  dcat: http://www.w3.org/ns/dcat#
  dcatap: http://data.europa.eu/r5r/
  dct: http://purl.org/dc/terms/
  eli: http://data.europa.eu/eli/ontology#
  foaf: http://xmlns.com/foaf/0.1/
  locn: http://www.w3.org/ns/locn#
  odrl: http://www.w3.org/ns/odrl/2/
  prov: http://www.w3.org/ns/prov#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sh: http://www.w3.org/ns/shacl#
  skos: http://www.w3.org/2004/02/skos/core#
  spdx: http://spdx.org/rdf/terms#
  time: http://www.w3.org/2006/time#
  vcard: http://www.w3.org/2006/vcard/ns#
  xsd: http://www.w3.org/2001/XMLSchema#

dataSources:
  nodeShapes:
    resolver: sparql
    location: sparql/nodeShapes.rq
    source:
      - /shapes/dcat-ap-SHACL.ttl
      - /shapes/dcat-ap-OPT.ttl
      - /shapes/dcat-ap-nl-SHACL.ttl
      - /shapes/dcat-ap-nl-SHACL-codelist-range.ttl
      - /shapes/dcat-ap-nl-OPT.ttl
      - /shapes/optionaliteit.ttl
    resultFrame:
      _key: targetClass
      targetClass:
        _value: targetClass
        _prefix: true
      propertyShapes:
        _key: property
        _orderBy: +propertyName
        propertyName: propertyName
        property: property
        shape:
          _type: string
          _value: propertyShape
          _map: join
        propertyPrefixed:
          _value: property
          _prefix: true
        description: description
        class: class
        classPrefixed:
          _value: class
          _prefix: true
        datatype: datatype
        datatypePrefixed:
          _value: datatype
          _prefix: true
        nodeShapeName: nodeShapeName
        nodeShapeSeeAlso: nodeShapeSeeAlso
        nodeKind: nodeKind
        nodeKindPrefixed:
          _value: nodeKind
          _prefix: true
        minCount: minCount
        maxCount: maxCount
        optionaliteit:
          _value: optionaliteit
          _type: set

templates:
  - templateLocation: klassen.md
    outputLocation: /doc/gen/
  - templateLocation: ondersteunendeKlassen.md
    outputLocation: /doc/gen/
